#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlIO-subfile
version:      0.07
version_from: subfile.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
